/*

 INTRO_SCREEN_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 197

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define intro_screen_tilesBank 0
/* Start of tile array. */
extern unsigned char intro_screen_tiles[];

/* End of INTRO_SCREEN_TILES.H */
