/*

 SRC/END_GAME_MAP_WINDOW.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 11
   Tile set      : end_game_screen.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define end_game_map_windowWidth 20
#define end_game_map_windowHeight 11
#define end_game_map_windowBank 0

extern unsigned char end_game_map_window[];

/* End of SRC/END_GAME_MAP_WINDOW.H */
