/*

 SRC/END_GAME_MAP_BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : end_game_screen.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define end_game_map_bgWidth 20
#define end_game_map_bgHeight 18
#define end_game_map_bgBank 0

extern unsigned char end_game_map_bg[];

/* End of SRC/END_GAME_MAP_BG.H */
