/*

 SRC/GAME_OVER_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : game_over_screen.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define game_over_mapWidth 20
#define game_over_mapHeight 18
#define game_over_mapBank 0

extern unsigned char game_over_map[];

/* End of SRC/GAME_OVER_MAP.H */
