/*

 SRC/INTRO_DREAM_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : end_game_screen.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define intro_dream_mapWidth 20
#define intro_dream_mapHeight 18
#define intro_dream_mapBank 0

extern unsigned char intro_dream_map[];

/* End of SRC/INTRO_DREAM_MAP.H */
