/*

 SRC/INTRO_SCREEN_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : intro_screen.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define intro_screen_mapWidth 20
#define intro_screen_mapHeight 18
#define intro_screen_mapBank 0

extern unsigned char intro_screen_map[];

/* End of SRC/INTRO_SCREEN_MAP.H */
