/*

 JOSIE_CALL_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : josie_call_screen.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define josie_call_mapWidth 20
#define josie_call_mapHeight 18
#define josie_call_mapBank 0

extern unsigned char josie_call_map[];

/* End of JOSIE_CALL_MAP.H */
