/*

 SRC/KITCHENCOUNTER_MAP_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 80 x 18
   Tile set      : kitchen_counter.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define kitchencounter_map_1Width 80
#define kitchencounter_map_1Height 18
#define kitchencounter_map_1Bank 0

extern unsigned char kitchencounter_map_1[];

/* End of SRC/KITCHENCOUNTER_MAP_1.H */
