/*

 SRC/KITCHENCOUNTER_MAP_3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 80
   Tile set      : kitchen_counter.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define kitchencounter_map_3Width 20
#define kitchencounter_map_3Height 80
#define kitchencounter_map_3Bank 0

extern unsigned char kitchencounter_map_3[];

/* End of SRC/KITCHENCOUNTER_MAP_3.H */
