/*

 LIVING_ROOM_MAP_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 80 x 18
   Tile set      : living_room_1.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define living_room_map_1Width 80
#define living_room_map_1Height 18
#define living_room_map_1Bank 0

extern unsigned char living_room_map_1[];

/* End of LIVING_ROOM_MAP_1.H */
