/*

 LIVING_ROOM_SHARED_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 81

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define living_room_tiles_2Bank 0
/* Start of tile array. */
extern unsigned char living_room_tiles_2[];

/* End of LIVING_ROOM_SHARED_TILES.H */
