/*

 MATCHY_CHECKLIST_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : josie_call_screen.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define matchy_checklist_mapWidth 20
#define matchy_checklist_mapHeight 18
#define matchy_checklist_mapBank 0

extern unsigned char matchy_checklist_map[];

/* End of MATCHY_CHECKLIST_MAP.H */
